### ISSUE TITLE
Doesn't work in NextJS 13.2.4

### ISSUE THREAD

**Issue by rwu823** [lingui/swc-plugin#39] opened 2023-03-16 00:39 UTC
Adding this swc plugin causes the next dev server to fail to start.

```js
// next.config.js
  experimental: {
    swcPlugins: [['@lingui/swc-plugin', {}]],
  },
```

It is worked fine before upgrading Next.js

**Comment by thekip** [comment] 2023-03-16 16:19
i believe they simply bumped a bundled version of SWC, so now layout of AST is not compatible with current compiled version.

**Comment by rwu823** [comment] 2023-03-16 23:59
@andrii-bodnar The [nextjs-13 example](https://github.com/lingui/swc-plugin/tree/main/examples/nextjs-13) doesn't upgrade to the latest next.


https://github.com/lingui/swc-plugin/blob/main/examples/nextjs-13/package.json#L20

```json
 "next": "13.1.2",
```

**Comment by khmm12** [comment] 2023-03-17 13:38
Yep, the plugin doesn't work with @swc/core >= 1.3.39.

**Comment by vitorbertolucci** [comment] 2023-03-24 12:40
I may be missing something but it seems that NextJS 13.2.4 is using @swc/core 1.2.203 (https://github.com/vercel/next.js/blob/v13.2.4/package.json) and the @lingui/swc-plugin is breaking it, so it is not only for @swc/core >= 1.3.39

**Comment by thekip** [comment] 2023-03-27 08:49
Current stable version of the plugin compiled with swc_core "0.56.1" that according to [Selecting swc_core](https://swc.rs/docs/plugin/selecting-swc-core) 

<img width="477" alt="image" src="https://user-images.githubusercontent.com/1586852/227890996-9ce1fe44-5054-4cf9-beed-6b9b41debf8c.png">

**Comment by thekip** [comment] 2023-03-27 17:20
Do you guys know any custom SWC plugins which works with latest nextjs? I want to take it as an example.

**Comment by thekip** [comment] 2023-03-29 06:37
FYI https://github.com/vercel/next.js/issues/46989

**Comment by bigint** [comment] 2023-04-07 10:28
<img width="992" alt="Screenshot 2023-04-07 at 3 57 44 PM" src="https://user-images.githubusercontent.com/69431456/230593317-4fbbce26-2f4b-4960-a31d-263ec5b2795b.png">

I'm getting this in my project 🙇🏼 any ideas how to fix

https://github.com/lensterxyz/lenster

**Comment by bigint** [comment] 2023-04-07 10:31
https://github.com/vercel/next.js/issues/46989#issuecomment-1493911169

**Comment by thekip** [comment] 2023-04-07 10:45
> I'm getting this in my project 🙇🏼 any ideas how to fix

Downgrade to nextjs < 13.2.4 
Latest next-swc has a bug, waiting [this](https://github.com/vercel/turbo/pull/4470) to be merged

**Comment by TimFL** [comment] 2023-04-20 08:04
Looks like [v13.3.1-canary.12](https://github.com/vercel/next.js/releases/tag/v13.3.1-canary.12) fixes this issue.

**Comment by thekip** [comment] 2023-04-20 08:21
@TimFL did you try the current version of a plugin with canary release, or just notices that the fix was merged by nextjs team?  I'm asking because whont to know should i rebuild plugin with latest swc-core to support [v13.3.1-canary.12](https://github.com/vercel/next.js/releases/tag/v13.3.1-canary.12) or it works as is.

**Comment by TimFL** [comment] 2023-04-20 08:22
> @TimFL did you try the current version of a plugin with canary release, or just noticed that the fix was merged by nextjs team? I'm asking because whont to know should i rebuild plugin with latest swc-core to support [v13.3.1-canary.12](https://github.com/vercel/next.js/releases/tag/v13.3.1-canary.12) or it works as is.

I'm sorry for the confusion, I meant: that release fixes the swc problems, but plugin devs have to update their libraries so they work again. This needs updating now.

**Comment by hehex9** [comment] 2023-04-20 10:26
I've tested the latest version of swc_core (0.75) with the newest next.js canary release, and I can confirm that the wasm file can be executed without any issues.

**Comment by thekip** [comment] 2023-04-24 14:27
https://github.com/lingui/swc-plugin/pull/54/files

**Comment by thekip** [comment] 2023-04-26 14:46
v4 is relased officially and it's already built with latest `swc-core`. Please see [compatibility table](https://github.com/lingui/swc-plugin#compatibility) in readme

**Closed by thekip** 2023-04-26 14:46 UTC
Labels: bug, help wanted

**Comment by pawanrana1992** [comment] 2023-07-07 07:41
I am also trying to use  [Typewind](https://typewind.vercel.app/docs/examples/next) with tailwind config. but it is not working. It seems we can't use any custom plugin with nextjs 13.x.

Also If i am trying to use babel. then its working fine but not able to use most of the latest support from nextjs 13 like `fonts` giving error. it is asking SWC environment.

Nextjs team please help fix this or give me a workaround to move further. it is extremely required for us.

I also raise some query on [Typewind](https://github.com/Mokshit06/typewind/issues/50) but it is related to Nextjs 13.x

**Comment by thekip** [comment] 2023-07-07 07:44
@pawanrana1992 please read [compatibility table](https://github.com/lingui/swc-plugin#compatibility) **carefully**. The plugins indeed work with nextjs 13.*. You need to choose the right version of both. SWC plugins is experimental feature, they DO BREAK backward compatibility in patch and minor releases, so you need to choose an **exact version** of nextjs
